In [32]:
import cellxgene_census
import pandas as pd

In [68]:
census = cellxgene_census.open_soma(census_version="2023-07-25")

# Blood tissue

In [69]:
summary_table = census["census_info"]["summary_cell_counts"].read().concat().to_pandas()
summary_table.query("organism == 'Homo sapiens' & category == 'tissue_general' & label =='blood'")

,soma_joinid,organism,category,ontology_term_id,unique_cell_count,total_cell_count,label
953,953,Homo sapiens,tissue_general,UBERON:0000178,8758448,9500464,blood

In [70]:
blood_obs = (
    census["census_data"]["homo_sapiens"]
    .obs.read(value_filter="tissue_general == 'blood' and is_primary_data == True")
    .concat()
    .to_pandas()
)
blood_obs

,soma_joinid,dataset_id,assay,assay_ontology_term_id,cell_type,cell_type_ontology_term_id,development_stage,development_stage_ontology_term_id,disease,disease_ontology_term_id,...,is_primary_data,self_reported_ethnicity,self_reported_ethnicity_ontology_term_id,sex,sex_ontology_term_id,suspension_type,tissue,tissue_ontology_term_id,tissue_general,tissue_general_ontology_term_id
0,114832,74cff64f-9da9-4b2a-9b3b-8a04a1598040,10x 3' v2,EFO:0009899,T cell,CL:0000084,unknown,unknown,normal,PATO:0000461,...,True,unknown,unknown,female,PATO:0000383,cell,blood,UBERON:0000178,blood,UBERON:0000178
1,114833,74cff64f-9da9-4b2a-9b3b-8a04a1598040,10x 3' v2,EFO:0009899,T cell,CL:0000084,unknown,unknown,normal,PATO:0000461,...,True,unknown,unknown,female,PATO:0000383,cell,blood,UBERON:0000178,blood,UBERON:0000178
2,114834,74cff64f-9da9-4b2a-9b3b-8a04a1598040,10x 3' v2,EFO:0009899,T cell,CL:0000084,unknown,unknown,normal,PATO:0000461,...,True,unknown,unknown,female,PATO:0000383,cell,blood,UBERON:0000178,blood,UBERON:0000178
3,114835,74cff64f-9da9-4b2a-9b3b-8a04a1598040,10x 3' v2,EFO:0009899,T cell,CL:0000084,unknown,unknown,normal,PATO:0000461,...,True,unknown,unknown,female,PATO:0000383,cell,blood,UBERON:0000178,blood,UBERON:0000178
4,114836,74cff64f-9da9-4b2a-9b3b-8a04a1598040,10x 3' v2,EFO:0009899,T cell,CL:0000084,unknown,unknown,normal,PATO:0000461,...,True,unknown,unknown,female,PATO:0000383,cell,blood,UBERON:0000178,blood,UBERON:0000178
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8758443,56398380,8c42cfd0-0b0a-46d5-910c-fc833d83c45e,10x 3' v2,EFO:0009899,megakaryocyte,CL:0000556,51-year-old human stage,HsapDv:0000145,normal,PATO:0000461,...,True,unknown,unknown,female,PATO:0000383,cell,blood,UBERON:0000178,blood,UBERON:0000178
8758444,56398381,8c42cfd0-0b0a-46d5-910c-fc833d83c45e,10x 3' v2,EFO:0009899,megakaryocyte,CL:0000556,51-year-old human stage,HsapDv:0000145,normal,PATO:0000461,...,True,unknown,unknown,female,PATO:0000383,cell,blood,UBERON:0000178,blood,UBERON:0000178
8758445,56398382,8c42cfd0-0b0a-46d5-910c-fc833d83c45e,10x 3' v2,EFO:0009899,megakaryocyte,CL:0000556,51-year-old human stage,HsapDv:0000145,normal,PATO:0000461,...,True,unknown,unknown,female,PATO:0000383,cell,blood,UBERON:0000178,blood,UBERON:0000178
8758446,56398383,8c42cfd0-0b0a-46d5-910c-fc833d83c45e,10x 3' v2,EFO:0009899,megakaryocyte,CL:0000556,51-year-old human stage,HsapDv:0000145,normal,PATO:0000461,...,True,unknown,unknown,female,PATO:0000383,cell,blood,UBERON:0000178,blood,UBERON:0000178
8758447,56398384,8c42cfd0-0b0a-46d5-910c-fc833d83c45e,10x 3' v2,EFO:0009899,megakaryocyte,CL:0000556,51-year-old human stage,HsapDv:0000145,normal,PATO:0000461,...,True,unknown,unknown,female,PATO:0000383,cell,blood,UBERON:0000178,blood,UBERON:0000178

In [71]:
census_datasets = (
    census["census_info"]["datasets"]
    .read(column_names=["collection_name", "dataset_title", "dataset_id", "soma_joinid"])
    .concat()
    .to_pandas()
)
census_datasets = census_datasets.set_index("dataset_id")
census_datasets

,collection_name,dataset_title,soma_joinid
dataset_id,,,
f171db61-e57e-4535-a06a-35d8b6ef8f2b,Spatial multiomics map of trophoblast developm...,donor_p13_trophoblasts,0
ecf2e08e-2032-4a9e-b466-b65b395f4a02,Spatial multiomics map of trophoblast developm...,All donors trophoblasts,1
74cff64f-9da9-4b2a-9b3b-8a04a1598040,Spatial multiomics map of trophoblast developm...,All donors all cell states (in vivo),2
5af90777-6760-4003-9dba-8f945fec6fdf,Mapping single-cell transcriptomes in the intr...,Single-cell transcriptomic datasets of Renal c...,3
bd65a70f-b274-4133-b9dd-0d1431b6af34,Single-cell sequencing links multiregional imm...,Single-cell sequencing links multiregional imm...,4
...,...,...,...
f9ad5649-f372-43e1-a3a8-423383e5a8a2,Molecular characterization of selectively vuln...,Molecular characterization of selectively vuln...,588
456e8b9b-f872-488b-871d-94534090a865,Single-cell atlas of peripheral immune respons...,Single-cell atlas of peripheral immune respons...,589
2adb1f8a-a6b1-4909-8ee8-484814e2d4bf,Construction of a human cell landscape at sing...,Construction of a human cell landscape at sing...,590
e04daea4-4412-45b5-989e-76a9be070a89,A molecular cell atlas of the human lung from ...,"Krasnow Lab Human Lung Cell Atlas, Smart-seq2",591
8c42cfd0-0b0a-46d5-910c-fc833d83c45e,A molecular cell atlas of the human lung from ...,"Krasnow Lab Human Lung Cell Atlas, 10X",592

In [72]:
dataset_cell_counts = pd.DataFrame(blood_obs[["dataset_id"]].value_counts())
dataset_cell_counts = dataset_cell_counts.rename(columns={0: "cell_counts"})
dataset_cell_counts = dataset_cell_counts.merge(census_datasets, on="dataset_id")

dataset_cell_counts

,count,collection_name,dataset_title,soma_joinid
dataset_id,,,,
9dbab10c-118d-496b-966a-67f1763a6b7d,1399186,COVID-19 immune features revealed by a large-s...,Large-scale single-cell analysis reveals criti...,482
218acb0f-9f2f-4f76-b90b-15a4b7c7f629,1263676,Single-cell RNA-seq reveals the cell-type-spec...,multiplexed scRNA-seq of 1.2 million PBMCs fro...,447
3faad104-2ab8-4434-816d-474d8d2641db,1248980,Single-cell eQTL mapping identifies cell type ...,Single-cell eQTL mapping identifies cell type ...,417
b0e547f0-462b-4f81-b31b-5b0a5d96f537,1058909,Asian Immune Diversity Atlas (AIDA),"AIDA Phase 1: Chinese, Indian, Japanese, Korea...",57
ebc2e1ff-c8f9-466a-acf4-9d291afaf8b3,836148,A blood atlas of COVID-19 defines hallmarks of...,COMBAT project: single cell gene expression da...,427
c7775e88-49bf-4ba2-a03b-93f00447c958,647366,Single-cell multi-omics analysis of the immune...,Single-cell multi-omics analysis of the immune...,445
01ad3cd7-3929-4654-84c0-6db05bd5fd59,600929,Type I interferon autoantibodies are associate...,Type I interferon autoantibodies are associate...,457
2a498ace-872a-4935-984b-1afa70fd9886,339597,Local and systemic responses to SARS-CoV-2 inf...,PBMC,421
21d3e683-80a4-4d9b-bc89-ebb2df513dde,246964,Time-resolved Systems Immunology Reveals a Lat...,Time-resolved Systems Immunology Reveals a Lat...,509
ed5d841d-6346-47d4-ab2f-7119ad7e3a35,161764,Integrated analysis of multimodal single-cell ...,nygc multimodal pbmc,348
0c774045-26a7-40f8-9b07-6742d3c771c0,133405,Single cell RNA sequencing of CD19 CAR T-cell ...,Single cell RNA sequencing of CD19 CAR T-cell ...,407
30cd5311-6c09-46c9-94f1-71fe4b91813c,125117,Time-resolved Systems Immunology Reveals a Lat...,Time-resolved Systems Immunology Reveals a Lat...,508
c2a461b1-0c15-4047-9fcb-1f966fe55100,97499,Sampling peripheral blood and matched nasal sw...,Autoimmunity PBMCs,418
3c75a463-6a87-4132-83a8-c3002624394d,95064,Single-cell Atlas of common variable immunodef...,Activated PBMCs - Expanded cohort CITE-seq,126
5af90777-6760-4003-9dba-8f945fec6fdf,60084,Mapping single-cell transcriptomes in the intr...,Single-cell transcriptomic datasets of Renal c...,3
de2c780c-1747-40bd-9ccf-9588ec186cee,59572,Immunophenotyping of COVID-19 and influenza hi...,Immunophenotyping of COVID-19 and influenza hi...,431
fa8605cf-f27e-44af-ac2a-476bee4410d3,59506,Acute COVID-19 cohort across a range of WHO ca...,PBMCs,419
53d208b0-2cfd-4366-9866-c3c6114081bc,50115,Tabula Sapiens,Tabula Sapiens - All Cells,475
59b69042-47c2-47fd-ad03-d21beb99818f,49139,A Web Portal and Workbench for Biological Diss...,Individual Single-Cell RNA-seq PBMC Data from ...,568
456e8b9b-f872-488b-871d-94534090a865,44721,Single-cell atlas of peripheral immune respons...,Single-cell atlas of peripheral immune respons...,589
2adb1f8a-a6b1-4909-8ee8-484814e2d4bf,40829,Construction of a human cell landscape at sing...,Construction of a human cell landscape at sing...,590
bd65a70f-b274-4133-b9dd-0d1431b6af34,35838,Single-cell sequencing links multiregional imm...,Single-cell sequencing links multiregional imm...,4
1b9d8702-5af8-4142-85ed-020eb06ec4f6,27620,Cross-tissue immune cell analysis reveals tiss...,Global,411
01209dce-3575-4bed-b1df-129f57fbc031,17625,Single-cell transcriptomics of human T cells r...,Single-cell transcriptomics of human T cells r...,531
d7d7e89c-c93a-422d-8958-9b4a90b69558,16901,Single-cell Atlas of common variable immunodef...,Activated PBMCs - Twins scRNA-seq,124
5bc42b88-bb76-4954-927b-8bb7369adc64,11266,Single-cell reconstruction of the early matern...,Pregnant Uterus (All),137
74cff64f-9da9-4b2a-9b3b-8a04a1598040,10989,Spatial multiomics map of trophoblast developm...,All donors all cell states (in vivo),2
d3566d6a-a455-4a15-980f-45eb29114cab,7145,Single-cell proteo-genomic reference maps of t...,blood and bone marrow from a healthy young donor,327
471647b3-04fe-4c76-8372-3264feb950e8,5749,Blood and immune development in human fetal bo...,"CD34+ Fetal Bone Marrow, Fetal Liver, Cord Blo...",278
8c42cfd0-0b0a-46d5-910c-fc833d83c45e,4669,A molecular cell atlas of the human lung from ...,"Krasnow Lab Human Lung Cell Atlas, 10X",592
a5d95a42-0137-496f-8a60-101e17f263c8,1324,Single-cell Atlas of common variable immunodef...,Steady-state B cells - scRNA-seq,125
e04daea4-4412-45b5-989e-76a9be070a89,752,A molecular cell atlas of the human lung from ...,"Krasnow Lab Human Lung Cell Atlas, Smart-seq2",591

In [56]:
adata = cellxgene_census.get_anndata(
    census=census,
    organism="Homo sapiens",
    #var_value_filter="feature_id in ['ENSG00000161798', 'ENSG00000188229']",
    obs_value_filter='development_stage != "unknown" and tissue_general == "blood" and is_primary_data==True and disease == "normal"',
    #column_names={"obs": ["sex", "development_stage", "self_reported_ethnicity", "assay", "dataset_id"
)

In [60]:
adata.obs['development_stage'].unique()

array(['57-year-old human stage', '46-year-old human stage',
       '43-year-old human stage', '58-year-old human stage',
       '33-year-old human stage', '65-year-old human stage',
       '68-year-old human stage', '21-year-old human stage',
       '47-year-old human stage', '41-year-old human stage',
       '56-year-old human stage', '44-year-old human stage',
       '53-year-old human stage', '40-year-old human stage',
       '67-year-old human stage', '62-year-old human stage',
       '45-year-old human stage', '55-year-old human stage',
       '64-year-old human stage', '30-year-old human stage',
       '35-year-old human stage', '49-year-old human stage',
       '54-year-old human stage', '61-year-old human stage',
       '52-year-old human stage', '60-year-old human stage',
       '48-year-old human stage', '31-year-old human stage',
       '50-year-old human stage', '37-year-old human stage',
       '42-year-old human stage', '36-year-old human stage',
       '66-year-old human stage', '23-year-old human stage',
       '51-year-old human stage', '38-year-old human stage',
       '39-year-old human stage', '32-year-old human stage',
       '72-year-old human stage', '75-year-old human stage',
       '59-year-old human stage', '34-year-old human stage',
       '69-year-old human stage', '63-year-old human stage',
       '26-year-old human stage', '24-year-old human stage',
       '27-year-old human stage', '28-year-old human stage',
       '25-year-old human stage', '22-year-old human stage',
       '29-year-old human stage', '73-year-old human stage',
       '71-year-old human stage', '19-year-old human stage',
       'newborn human stage', 'seventh decade human stage',
       'sixth decade human stage', '88-year-old human stage',
       '78-year-old human stage', '74-year-old human stage',
       '84-year-old human stage', '81-year-old human stage',
       '76-year-old human stage', '77-year-old human stage',
       '70-year-old human stage', '79-year-old human stage',
       '91-year-old human stage', '80-year-old human stage',
       '85-year-old human stage', '87-year-old human stage',
       '86-year-old human stage', '89-year-old human stage',
       '83-year-old human stage', '95-year-old human stage',
       '82-year-old human stage', '90-year-old human stage',
       '97-year-old human stage', '94-year-old human stage',
       '96-year-old human stage', '20-year-old human stage',
       '93-year-old human stage', '65-79 year-old human stage',
       'human adult stage', 'human aged stage', 'infant stage',
       '2-5 year-old child stage', '6-12 year-old child stage',
       'adolescent stage', '7-year-old human stage',
       '5-year-old human stage', '4-year-old human stage',
       '6-year-old human stage', 'third decade human stage',
       'fourth decade human stage', 'fifth decade human stage',
       '80 year-old and over human stage'], dtype=object)

In [64]:
X = pd.DataFrame(adata.X[:110, :110].todense())

In [67]:
X[0].value_counts()

0
0.0    92
1.0    11
3.0     4
2.0     3
Name: count, dtype: int64